/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo3p;

import static java.lang.String.valueOf;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brayan Cifuentes
 */
public class Asignacion_cursos_maestros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Empleados
     */

    public Asignacion_cursos_maestros() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbx_carrera = new javax.swing.JComboBox<>();
        lbl_carrera = new javax.swing.JLabel();
        cbx_sede = new javax.swing.JComboBox<>();
        lbl_sede = new javax.swing.JLabel();
        cbx_jornada = new javax.swing.JComboBox<>();
        lbl_jornada = new javax.swing.JLabel();
        cbx_seccion = new javax.swing.JComboBox<>();
        lbl_seccion = new javax.swing.JLabel();
        lbl_aula = new javax.swing.JLabel();
        cbx_aula = new javax.swing.JComboBox<>();
        cbx_curso = new javax.swing.JComboBox<>();
        lbl_curso = new javax.swing.JLabel();
        cbx_maestro = new javax.swing.JComboBox<>();
        lbl_maestro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_asignacion = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Asignación Cursos a Maestros");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Carrera:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Codigo Sede:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Codigo Jornada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ingresa el código de Maestro: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        txt_buscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 530, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busquedap.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 60, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardarp.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 60, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 60, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Codigo Seccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Codigo Aula:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 282, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Codigo Curso:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 307, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Codigo Maestro:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 335, -1, -1));

        cbx_carrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_carreraMouseClicked(evt);
            }
        });
        cbx_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_carreraActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 170, 130, -1));

        lbl_carrera.setText("Codigo");
        getContentPane().add(lbl_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 173, -1, -1));

        cbx_sede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_sedeMouseClicked(evt);
            }
        });
        cbx_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_sedeActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 198, 130, -1));

        lbl_sede.setText("Codigo");
        getContentPane().add(lbl_sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 201, -1, -1));

        cbx_jornada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_jornadaMouseClicked(evt);
            }
        });
        cbx_jornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_jornadaActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_jornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 226, 130, -1));

        lbl_jornada.setText("Codigo");
        getContentPane().add(lbl_jornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 229, -1, -1));

        cbx_seccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_seccionMouseClicked(evt);
            }
        });
        cbx_seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_seccionActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 254, 130, -1));

        lbl_seccion.setText("Codigo");
        getContentPane().add(lbl_seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 257, -1, -1));

        lbl_aula.setText("Codigo");
        getContentPane().add(lbl_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 285, -1, -1));

        cbx_aula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_aulaMouseClicked(evt);
            }
        });
        cbx_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_aulaActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 282, 130, -1));

        cbx_curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_cursoMouseClicked(evt);
            }
        });
        cbx_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cursoActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 307, 130, -1));

        lbl_curso.setText("Codigo");
        getContentPane().add(lbl_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 310, -1, -1));

        cbx_maestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_maestroMouseClicked(evt);
            }
        });
        cbx_maestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_maestroActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 335, 130, -1));

        lbl_maestro.setText("Codigo");
        getContentPane().add(lbl_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 335, -1, -1));

        tbl_asignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Carrera", "Codigo Sede", "Codigo Jornada", "Codigo Seccion", "Codigo Aula", "Codigo Curso", "Codigo Maestro"
            }
        ));
        tbl_asignacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_asignacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_asignacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 162, 654, 124));

        jButton5.setText("Listar Datos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 306, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbx_carreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_carreraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_carreraMouseClicked

    private void cbx_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_carreraActionPerformed

    }//GEN-LAST:event_cbx_carreraActionPerformed

    private void cbx_sedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_sedeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbx_sedeMouseClicked

    private void cbx_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_sedeActionPerformed
        
    }//GEN-LAST:event_cbx_sedeActionPerformed

    private void cbx_jornadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_jornadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_jornadaMouseClicked

    private void cbx_jornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_jornadaActionPerformed
        
    }//GEN-LAST:event_cbx_jornadaActionPerformed

    private void cbx_seccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_seccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_seccionMouseClicked

    private void cbx_seccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_seccionActionPerformed
       
    }//GEN-LAST:event_cbx_seccionActionPerformed

    private void cbx_aulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_aulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_aulaMouseClicked

    private void cbx_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_aulaActionPerformed
       
    }//GEN-LAST:event_cbx_aulaActionPerformed

    private void cbx_cursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_cursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cursoMouseClicked

    private void cbx_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cursoActionPerformed
       
    }//GEN-LAST:event_cbx_cursoActionPerformed

    private void cbx_maestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_maestroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_maestroMouseClicked

    private void cbx_maestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_maestroActionPerformed
        
    }//GEN-LAST:event_cbx_maestroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbl_asignacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_asignacionMouseClicked
        
    }//GEN-LAST:event_tbl_asignacionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_aula;
    private javax.swing.JComboBox<String> cbx_carrera;
    private javax.swing.JComboBox<String> cbx_curso;
    private javax.swing.JComboBox<String> cbx_jornada;
    private javax.swing.JComboBox<String> cbx_maestro;
    private javax.swing.JComboBox<String> cbx_seccion;
    private javax.swing.JComboBox<String> cbx_sede;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_aula;
    private javax.swing.JLabel lbl_carrera;
    private javax.swing.JLabel lbl_curso;
    private javax.swing.JLabel lbl_jornada;
    private javax.swing.JLabel lbl_maestro;
    private javax.swing.JLabel lbl_seccion;
    private javax.swing.JLabel lbl_sede;
    private javax.swing.JTable tbl_asignacion;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
