/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo2p;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javafx.scene.layout.Pane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan Cifuentes
 */
public class Ingreso_Notas extends javax.swing.JInternalFrame {
  
    /**
     * Creates new form Ingreso_Notas
     */
    public Ingreso_Notas() {
        initComponents();
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JTabbedPane();
        panel_maestro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoMaestro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbx_sede = new javax.swing.JComboBox<String>();
        cbx_carrera = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        cbx_jornada = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        cbx_seccion = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        cbx_aula = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        cbx_curso = new javax.swing.JComboBox<String>();
        lblCarrera = new javax.swing.JLabel();
        lblSede = new javax.swing.JLabel();
        lbl_jornada = new javax.swing.JLabel();
        lbl_seccion = new javax.swing.JLabel();
        lbl_aula = new javax.swing.JLabel();
        lbl_curso = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        panel_nota = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbx_alumno = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        cbx_nota = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        panel_maestro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("REGISTRO:");
        panel_maestro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 34, -1, -1));

        jLabel5.setText("Codigo Maestro:");
        panel_maestro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 80, -1, -1));

        txtCodigoMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoMaestroActionPerformed(evt);
            }
        });
        panel_maestro.add(txtCodigoMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 77, 99, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_maestro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 103, -1, -1));

        jLabel2.setText("Codigo Carrera:");
        panel_maestro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 155, -1, -1));

        jLabel3.setText("Codigo Sede:");
        panel_maestro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 186, -1, -1));

        cbx_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_sedeActionPerformed(evt);
            }
        });
        panel_maestro.add(cbx_sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 183, 99, -1));

        cbx_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_carreraActionPerformed(evt);
            }
        });
        panel_maestro.add(cbx_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 152, 101, -1));

        jLabel4.setText("Codigo Jornada:");
        panel_maestro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 217, -1, -1));

        cbx_jornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_jornadaActionPerformed(evt);
            }
        });
        panel_maestro.add(cbx_jornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 214, 99, -1));

        jLabel6.setText("Codigo Seccion:");
        panel_maestro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 255, -1, -1));

        cbx_seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_seccionActionPerformed(evt);
            }
        });
        panel_maestro.add(cbx_seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 252, 99, -1));

        jLabel7.setText("Codigo Aula:");
        panel_maestro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 293, -1, -1));

        cbx_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_aulaActionPerformed(evt);
            }
        });
        panel_maestro.add(cbx_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 290, 99, -1));

        jLabel8.setText("Codigo Curso:");
        panel_maestro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 331, -1, -1));

        cbx_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cursoActionPerformed(evt);
            }
        });
        panel_maestro.add(cbx_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 328, 99, -1));

        lblCarrera.setText("Nombre");
        panel_maestro.add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 155, -1, -1));

        lblSede.setText("Nombre");
        panel_maestro.add(lblSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 186, -1, -1));

        lbl_jornada.setText("Nombre");
        panel_maestro.add(lbl_jornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 217, -1, -1));

        lbl_seccion.setText("Nombre");
        panel_maestro.add(lbl_seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 255, -1, -1));

        lbl_aula.setText("Nombre");
        panel_maestro.add(lbl_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 293, -1, -1));

        lbl_curso.setText("Nombre");
        panel_maestro.add(lbl_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 331, -1, -1));

        btnSiguiente.setText("Enviar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        panel_maestro.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        Panel.addTab("Registro Maestro", panel_maestro);

        panel_nota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("NOTAS:");
        panel_nota.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel10.setText("Carnet Alumno:");
        panel_nota.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        cbx_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_alumnoActionPerformed(evt);
            }
        });
        panel_nota.add(cbx_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 120, -1));

        jLabel11.setText("Tipo Nota:");
        panel_nota.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        cbx_nota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primer Parcial", "Segundo Parcial", "Tercer Parcial", "Actividades", "Extraordinario1", "Extraordinario2", "Recuperacion" }));
        cbx_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_notaActionPerformed(evt);
            }
        });
        panel_nota.add(cbx_nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, -1));

        jLabel12.setText("Nota (pts) : ");
        panel_nota.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        panel_nota.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 120, -1));

        lblTipo.setText("Codigo");
        panel_nota.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panel_nota.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Si el alumno no se\npresento o no se \nrealizo el examen\ncoloque 0 pts en la \nnota para poder \nrealizarle un Examen \nExtraordinario ");
        jScrollPane1.setViewportView(jTextArea1);

        panel_nota.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 210, 150));

        Panel.addTab("Ingreso Nota", panel_nota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbx_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_notaActionPerformed
        
    }//GEN-LAST:event_cbx_notaActionPerformed

    private void cbx_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_alumnoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbx_alumnoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void cbx_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cursoActionPerformed
        
    }//GEN-LAST:event_cbx_cursoActionPerformed

    private void cbx_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_aulaActionPerformed
        
    }//GEN-LAST:event_cbx_aulaActionPerformed

    private void cbx_seccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_seccionActionPerformed
        
    }//GEN-LAST:event_cbx_seccionActionPerformed

    private void cbx_jornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_jornadaActionPerformed
       
    }//GEN-LAST:event_cbx_jornadaActionPerformed

    private void cbx_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_carreraActionPerformed
        
    }//GEN-LAST:event_cbx_carreraActionPerformed

    private void cbx_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_sedeActionPerformed
        
    }//GEN-LAST:event_cbx_sedeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodigoMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMaestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMaestroActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbx_alumno;
    private javax.swing.JComboBox<String> cbx_aula;
    private javax.swing.JComboBox<String> cbx_carrera;
    private javax.swing.JComboBox<String> cbx_curso;
    private javax.swing.JComboBox<String> cbx_jornada;
    private javax.swing.JComboBox<String> cbx_nota;
    private javax.swing.JComboBox<String> cbx_seccion;
    private javax.swing.JComboBox<String> cbx_sede;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblSede;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lbl_aula;
    private javax.swing.JLabel lbl_curso;
    private javax.swing.JLabel lbl_jornada;
    private javax.swing.JLabel lbl_seccion;
    private javax.swing.JPanel panel_maestro;
    private javax.swing.JPanel panel_nota;
    private javax.swing.JTextField txtCodigoMaestro;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables
}
